# Site
name: "ictguru.nl"
title: "ictguru.nl"
description: "Dé site voor nieuwsgierige ICT-er!"
logo: 'assets/images/favicon.png'
favicon: 'assets/images/favicon.png'
github_username:  TobiasS1402
linkedin_username: tseijs
url: "https://v2.ictguru.nl"
baseurl: ""
include: ["_pages"]
permalink: /:title/
date_format: "%b %-d, %Y"

# Authors
authors:
  tobias:
    name: Tobias
    display_name: Tobias

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true


# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
